---
name: Build Docker Images

on:
  push: { branches: [master] }

jobs:
  ruby_270_ol8:
    name: Build Ruby 2.7.0 on Oracle Linux 8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        working-directory: 'oraclelinux:8'
        run: |
          docker build --tag jmanero/ruby:2.7.0-ol8 .
      - name: Push Image to Docker Hub
        run: |
          echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u jmanero --password-stdin
          docker push jmanero/ruby:2.7.0-ol8
