---
name: Build Docker Images

on:
  push: { branches: [master] }

jobs:
  ruby_270_ol8:
    name: Build Ruby 2.7.0 on Oracle Linux 8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          cd oraclelinux\:8
          docker build .
