---
name: Build Docker Images

on:
  push: { branches: [master] }

jobs:
  ruby_270_ol8:
    name: Build Ruby 2.7.0 on Oracle Linux 8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        env:
          build_id:  'GitHub :: ${{ github.repository }} :: ${{ github.workflow }} :: ${{ github.run_id }}'
          build_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

        run: |
          docker build  --file oraclelinux\:8/Dockerfile \
                        --build-arg BUILD_ID='${{ env.build_id }}' \
                        --build-arg BUILD_URL='${{ env.build_url }}' \
                        --tag jmanero/ruby:2.7.0-ol8 .

      - name: Push Image to Docker Hub
        run: |
          echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u jmanero --password-stdin
          docker push jmanero/ruby:2.7.0-ol8
